# -*- coding: utf-8 -*-
"""imageclassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1px1L67RnqD2fdMtdh1-NrUVHL3BakfAk
"""

from tensorflow.keras.datasets import cifar10

data=cifar10.load_data()

(x_train,y_train),(x_test,y_test)=data

x_train=x_train.astype("float")/255

x_test=x_test.astype("float")/255

from tensorflow.keras.utils import to_categorical
y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)

data=[1,2,3,4,5,6,7,8,9]

import matplotlib.pyplot as plt
for i in range(len(data)):
  plt.subplot(3,3,i+1)
  plt.imshow(x_train[i])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout

model=Sequential()

model.add(Conv2D(32,(3,3),activation="relu",padding="same",input_shape=(32,32,3)))
model.add(Conv2D(32,(3,3),activation="relu",padding="same",input_shape=(32,32,3)))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))
model.add(Conv2D(32,(3,3),activation="relu",padding="same"))
model.add(Conv2D(32,(3,3),activation="relu",padding="same"))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))
model.add(Conv2D(32,(3,3),activation="relu",padding="same"))
model.add(Conv2D(32,(3,3),activation="relu",padding="same"))
model.add(MaxPooling2D((2,2)))
model.add(Flatten())
model.add(Dense(10,activation="relu"))

model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen=ImageDataGenerator()

datagen.fit(x_train)

model.fit(datagen.flow(x_train,y_train,batch_size=52),epochs=2,validation_data=(x_test,y_test))

def predict(s):
  plt.figure(figsize=(1,1))
  plt.imshow(x_test[s])

predict(6)